<?php

/**
 * @file
 * A.
 */

/**
 * Implements hook_node_load().
 */
function webform_styles_node_load($nodes, $types) {
  // Iterate the node list.
  foreach ($nodes as $key => $node) {
    $results = db_select('webform_component')
      ->fields('webform_component', array('webform_styles', 'cid'))
      ->condition('nid', $node->nid, '=')
      ->execute();

    $styles = array();
    while ($record = $results->fetchAssoc()) {
      $styles[$record['cid']] = $record['webform_styles'];
      $node->webform_styles = unserialize($record['webform_styles']);
    }

    // Add the webform components into the node to later render them.
    //$node->webform_styles = $styles;

   // dpm($node->webform_styles);
  }
}

/**
 * Implements hook_webform_component_render_alter().
 */
function webform_styles_webform_component_render_alter(&$element, &$component) {
  if ($component['webform_styles']) {
    // Create the style array attribute if it doesn't exists.
    if (!isset($element['#attributes']['style'])) {
      $element['#attributes']['style'][] = array();
    }
    $element['#attributes']['style'] = $component['webform_styles'];

/**
 * Implements hook_form_webform_component_edit_form_alter().
 */
function webform_styles_form_webform_component_edit_form_alter(&$form, $component) {
  $form['webform_styles'] = array(
    '#type' => 'fieldset',
    '#title' => t('Inline styles'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#weight' => 5,
    'font-family' => array(
      '#type' => 'textfield',
      '#title' => t('Font Family'),
      '#description' => t('Specify font family to be used on the form field'),
      '#size' => 50,
      '#maxlength' => 255,
      '#weight' => 2,
    ),
    'font-size' => array(
      '#type' => 'textfield',
      '#title' => t('Font Size'),
      '#postfix' => t('Px'),
      '#description' => t('Specify font size to be used on the form field'),
      '#size' => 3,
      '#maxlength' => 3,
      '#weight' => 3,
    ),
    'color' => array(
      '#type' => 'textfield',
      '#title' => t('Color'),
      '#description' => t('Specify color to be used on the form field'),
      '#size' => 10,
      '#maxlength' => 20,
      '#weight' => 4,
    ),

/**
 * Implements webform_component_update().
 */
function webform_styles_webform_component_update($component) {

  $style = array();

  if (isset($component['webform_styles']['font-family'])) {
    $style["font-family"] = $component['webform_styles']['font-family'];
  }
  if (isset($component['webform_styles']['font-size'])) {
    $style["font-size"] = $component['webform_styles']['font-size'];
  }
  if (isset($component['webform_styles']['color'])) {
    $style["color"] = $component['webform_styles']['color'];
  }

  $result = db_update('webform_component')
    ->fields(array(
      'webform_styles' => serialize($style),
    ))
    ->condition('nid', (int) $component['nid'], '=')
    ->condition('cid', (int) $component['cid'], '=')
    ->execute();

}

/**
 * Implements webform_component_insert().
 */
function webform_styles_webform_component_insert($component) {
  webform_styles_webform_component_update($component);
}
