<?php

/**
 * @file
 * A.
 */

/**
 * Implements hook_init().
 */
function webform_styles_init(){

  drupal_add_css(drupal_get_path('module', 'webform_styles') . '/assets/swiper.min.css');
  drupal_add_css(drupal_get_path('module', 'webform_styles') . '/assets/webform_styles.css');

  drupal_add_js(drupal_get_path('module', 'webform_styles') . '/assets/swiper.jquery.min.js');
  drupal_add_js(drupal_get_path('module', 'webform_styles') . '/assets/webform_styles.js');
}

/**
 * Implements hook_node_load().
 */
function webform_styles_node_load($nodes, $types) {
  // Iterate the node list.
  foreach ($nodes as $key => $node) {
    $results = db_select('webform_component')
      ->fields('webform_component', array('webform_styles', 'cid'))
      ->condition('nid', $node->nid, '=')
      ->execute();

    $styles = array();
    while ($record = $results->fetchAssoc()) {
      $styles[$record['cid']] = $record['webform_styles'];
      $node->webform_styles = unserialize($record['webform_styles']);
    }
  }
}

/**
 * Implements hook_webform_component_render_alter().
 */
function webform_styles_webform_component_render_alter(&$element, &$component) {
  if ($component['webform_styles']) {

    // Create string from array, with styles separated by a semi-colon.
    $styles = implode('; ', array_map(
        function ($v, $k) {
          return sprintf("%s:%s", $k, $v);
        },
        unserialize($component['webform_styles']),
        array_keys(unserialize($component['webform_styles']))
    ));

    // Create the style array attribute if it doesn't exists.
    if (!isset($element['#attributes']['style'])) {
      $element['#attributes']['style'][] = array();
    }
    //$element['#attributes']['style'] = $component['webform_styles'];
    $element['#attributes']['style'] = $styles;
  }

  if ($component['webform_slide'] == 1) {
    $element['#post_render'] = array('webform_styles_post_render_slides');
  }
  
}


/**
 * Post-render of slides
 */
function webform_styles_post_render_slides($content, $element){

  // creating HTML for Swiper JS
  foreach($element['#options'] as $key => $value){
    if(!empty($key)){
      $swiper .= '<div class="swiper-slide">
                   <input class="swiper-input" id="'.$key.'" name="'.$key.'" type="text" data-placeholder="" value="'.$value.' '.$element['#description'].'" autocomplete="off" readonly="readonly">
                </div>';
    }
  }

  // we keep the drop-down, although will be hidden by CSS
  return '<div id="swiper-'.$element['#id'].'" class="swiper-container">
              <div class="swiper-wrapper">'
              .$swiper.
              '</div>
          </div>'.$content;
}


/**
 * Implements hook_form_webform_component_edit_form_alter().
 */
function webform_styles_form_webform_component_edit_form_alter(&$form, $component) {

  $nid = $form['nid']['#value'];
  $cid = $form['cid']['#value'];
  if ($cid == NULL) {
    $cid = 0;
  }

  // Fetch the class(es) of requested component.
  $webform_style = db_query("SELECT webform_styles FROM {webform_component} WHERE nid = :nid AND cid = :cid", array(':nid' => (int) $nid, ':cid' => (int) $cid))->fetchField();
  $styles = unserialize($webform_style);

  $form['webform_styles'] = array(
    '#type' => 'fieldset',
    '#title' => t('Inline styles'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#weight' => 5,
    'font-family' => array(
      '#type' => 'textfield',
      '#title' => t('Font Family'),
      '#description' => t('Specify font family to be used on the form field'),
      '#size' => 50,
      '#maxlength' => 255,
      '#weight' => 2,
      "#default_value" => isset($styles['font-family']) ? $styles['font-family'] : '',
    ),
    'font-size' => array(
      '#type' => 'textfield',
      '#title' => t('Font Size'),
      '#postfix' => t('px'),
      '#description' => t('Specify font size to be used on the form field'),
      '#size' => 5,
      '#maxlength' => 5,
      '#weight' => 3,
      "#default_value" => isset($styles['font-size']) ? $styles['font-size'] : '',
    ),
    'color' => array(
      '#type' => 'textfield',
      '#title' => t('Color'),
      '#description' => t('Specify color to be used on the form field'),
      '#size' => 10,
      '#maxlength' => 20,
      '#weight' => 4,
      "#default_value" => isset($styles['color']) ? $styles['color'] : '',
    ),
    'border' => array(
      '#type' => 'textfield',
      '#title' => t('Border'),
      '#description' => t('Specify the border size of the form field'),
      '#default_value' => isset($styles['border']) ? $styles['border'] : '',
      '#size' => 4,
      '#maxlength' => 6,
      '#weight' => 5,
    ),
    'margin' => array(
      '#type' => 'textfield',
      '#title' => t('Margin'),
      '#description' => t('Specify the margin of the form field'),
      '#default_value' => isset($styles['margin']) ? $styles['margin'] : '',
      '#size' => 4,
      '#maxlength' => 6,
      '#weight' => 6,
    ),
    'background-color' => array(
      '#type' => 'textfield',
      '#title' => t('Background Color'),
      '#description' => t('Specify background color to be used on the form field'),
      '#size' => 10,
      '#maxlength' => 20,
      '#weight' => 4,
      "#default_value" => isset($styles['background-color']) ? $styles['background-color'] : '',
    ),
  );

  if ($component['build_info']['args'][1]['type'] == 'select') {
    $webform_slide = db_query("SELECT webform_slide FROM {webform_component} WHERE nid = :nid AND cid = :cid", array(':nid' => (int) $nid, ':cid' => (int) $cid))->fetchField();
    $form['display']['slider'] = array(
      '#type' => 'checkbox',
      '#title' => t('Slider'),
      '#default_value' => $webform_slide,
      '#description' => t('Check this option if the option combo should be show as a slider.'),
      '#weight' => 0,
    );
  }

}

/**
 * Implements webform_component_update().
 */
function webform_styles_webform_component_update($component) {

  $style = array();

  foreach ($component['webform_styles'] as $key => $value) {
    $style[$key] = $value;
  }

  // if (isset($component['webform_styles']['font-family'])) {
  //   $style["font-family"] = $component['webform_styles']['font-family'];
  // }
  // if (isset($component['webform_styles']['font-size'])) {
  //   $style["font-size"] = $component['webform_styles']['font-size'];
  // }
  // if (isset($component['webform_styles']['color'])) {
  //   $style["color"] = $component['webform_styles']['color'];
  // }
  //  if (isset($component['webform_styles']['border'])) {
  //   $style["border"] = $component['webform_styles']['border'];
  // }
  //  if (isset($component['webform_styles']['margin'])) {
  //   $style["margin"] = $component['webform_styles']['margin'];
  // }

  $slider = 0;
  if (isset($component['display']['slider'])) {
    $slider = $component['display']['slider'];
  }

  $result = db_update('webform_component')
    ->fields(array(
      'webform_styles' => serialize($style),
      'webform_slide' => $slider,
    ))
    ->condition('nid', (int) $component['nid'], '=')
    ->condition('cid', (int) $component['cid'], '=')
    ->execute();

}

/**
 * Implements webform_component_insert().
 */
function webform_styles_webform_component_insert($component) {
  webform_styles_webform_component_update($component);
}


function webform_styles_form_element($variables) {

  $element = $variables['element'];
  // Disable radio button N/A
  if ($element['#type'] == 'radio' && $element['#return_value'] === '_none') {
    $variables['element']['#attributes']['disabled'] = TRUE;
  }
  return theme_form_element($variables);
}